### ISSUE TITLE
Downloading the target platform fails

### ISSUE THREAD

**Issue by moovida** [Polymap4/polymap4-p4#116]
Even if I granted permissions through my github account, I then get an: Access Denied

**Comment by fb71** [comment]
I'm checking this...

**Comment by fb71** [comment]
Jenkins permission issue. Working link is: http://46.4.28.8/download/mapzone/polymap4-targetplatform.zip

Build documentation updated. Can you please check this?

**Comment by moovida** [comment]
Yep, working now, thanks
