### ISSUE TITLE
[Import] Raster default style

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-p4#118]
Currently Grayscale is used as default style. This is bad as it directly maps values to color (gray) values. It might be better to have a COlorMap with grayscale.

**Comment by silviafranceschi** [comment]
Also remove the contrast enhancer from the raster symbolizer.

**Comment by fb71** [comment]
According to #136: Put the default raster style to the rainbow colormap

**Comment by fb71** [comment]
@moovida: the current version of the RAINBOW color map does not have an entry for novalues. Is this correct? Doesn't this cause unexpected render results for imported rasters with novalues? Do you think it is a good idea to have ELEVATION as default for imported data and RAINBOW for processing results?

**Comment by fb71** [comment]
ContrastEnhancer: is removed. However, renderer does not seem to honor. It "enhances" contrast even for this SLD:

'''
    <sld:FeatureTypeStyle>
        <sld:Name>Grayscale</sld:Name>
        <sld:Abstract>[No description]</sld:Abstract>
        <sld:Rule>
            <sld:RasterSymbolizer>
                <sld:ChannelSelection>
                    <sld:GrayChannel>
                        <sld:SourceChannelName>1</sld:SourceChannelName>
                    </sld:GrayChannel>
                </sld:ChannelSelection>
            </sld:RasterSymbolizer>
        </sld:Rule>
    </sld:FeatureTypeStyle>
'''

Do I miss something?

**Comment by moovida** [comment]
Just as a note: the colortables usually do not have an entry for the novalue. If elevation does, it has been added afterwards. Novalue should simply be rendered transparent.

**Comment by fb71** [comment]
Thanks for the note. In order to render novalues transparent there has to be an entry in the colormap with opacity 0 in SLD. ELEVATION has such an entry, hence novalues are transparent. RAINBOW does not have such an entry. Therefore, for RAINBOW novalues are rendered yellow instead of transparent.
