### ISSUE TITLE
[Mapzone] New user account creation

### ISSUE THREAD

**Issue by silviafranceschi** [Polymap4/polymap4-p4#120]
Creating a new user might be difficult, since the tooltip describing failure is not shown if the user doesn't hover the icon.

Example:

* username already exists
* if password is not coherent with the requirements

Possibly add possibility to recover passwords.

**Comment by fb71** [comment]
Foreground of form fields is set to red if input is invalid. Also tooltip is set.

@silviafranceschi, @moovida can you please check if this works better now?
