### ISSUE TITLE
pit_small_01 is not stylable - Mapzone

### ISSUE THREAD

**Issue by silviafranceschi** [Polymap4/polymap4-p4#129]
The UI freezes if the user tries to create a ColorMap for the pit_small_01.

**Comment by silviafranceschi** [comment]
It seems to be bound to the min-max calculation. The process stays active in the CPU and needs to be killed.

**Comment by fb71** [comment]
Pushed a quick fix. Not sure what's actually going on. Using more robust code from JGrasstools (OmsRasterSummary) is not currently possible because of http://github.com/Polymap4/polymap4-core/issues/108

**Comment by fb71** [comment]
Now, current version uses RenderedImage/Iterator code of @moovida. Seems to be much faster and fixes the problem. 80MB example processes 9458180 samples in 375ms. No progress monitor is shown at all for this amount of data :)
