### ISSUE TITLE
Create feature styler

### ISSUE THREAD

**Issue by joergreichert** [Polymap4/polymap4-p4#14]
* non functional requirements
   * simple / intuitive to use
     * e.g. hiding extra options in expert mode and using common default values for them?
     * offering only small, medium, large for size instead of concrete pixel values
     * offering predefined templates / style library
   * data to configure should be conform to SLD standard
   * WYSIWYG: preview of changes made in style editor in map

 * configuration
   * general
     * label
       * which data field to use for label, if any
       * font (font, size, color)
       * offset (from marker, from line, from polygon)
       * allow label overlap
     * line color (via color picker, RGB color)
     * line width (in pixel)
     * line opacity (0..1)
     * line border (see general)
   * point specific
     * marker color
     * marker symbol (image or type like ellipse)
     * marker opacity (0..1)
     * marker size (in pixel)
     * marker border (see general)
   * line specific
     * dash array (e.g. dotted line)
     * smooth factor (simplification of line when zooming out)
   * polygon specific
     * fill color
     * fill pattern (e.g. filling up space of polygon with repeating a symbol)
     * fill gradients (or is this done by rasters?)
     * polygon border (see general)
   * raster specific
     * defining color map entries with color and quantity
     * channel selection

[SLD cookbook](http://docs.geoserver.org/stable/en/user/styling/sld-cookbook/index.html)

 * actions
   * copy existing style to be used as template for defining a new style
   * inherit attributes from another style (attribute value = inherited)
   * generate default style (e.g. automatically select properties of feature like name to be used as label)
   * editing in SLD editor (or CSS Editor)
   * upload custom marker images
   * rule based styling, e.g. when feature property a is b then use fill color c

 * entry points
   * selecting/applying styles at features import (initially use default style)
   * changing style 
     * for a layer (style theme)
     * for a single feature in a layer

**Comment by stundzig** [comment]
Wow, was davon wollen wir jetzt sofort umsetzen?

**Comment by joergreichert** [comment]
Template-Implementation for defining a color picker in RAP: https://www.eclipse.org/forums/index.php/t/490096/

**Comment by joergreichert** [comment]
more details see https://github.com/Mapzone/mapzone/issues/14

**Comment by fb71** [comment]
Closing in favour of #84, #87 ff.
