### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by stundzig** [Polymap4/polymap4-p4#30]
Import for CSV files based on the new importer framework
 - [x] #31 
 - [x] #32 
 - [ ] #33 
 - [x] #42

**Comment by fb71** [comment]
Great! :) 

Ideas:

  - prompt for CSV delimiter and separator and quote char
  - name of Importer: "CSV: <filename>"  short and firm
  - headline prompt need BORDER around Text

**Comment by stundzig** [comment]
Its working now. Improvements and bugs are handled separately.
