### ISSUE TITLE
[Import] CSV: CRS selector

### ISSUE THREAD

**Issue by stundzig** [Polymap4/polymap4-p4#33]

**Comment by fb71** [comment]
Important for mapzone Go Live.

**Comment by fb71** [comment]
@stundzig: Das ist wirklich wichtig. Es wäre gut, wenn du dir das ansehen könntest. Wenn man das CRS nicht wählen kann, dann ist der CSV-Import, so schön er auch sein mag, praktisch nutzlos. Ich bin jetzt schon mehrfach darüber gestolpert: daten importiert, prima... X/Y ausgewählt, prima... nix in der karte zu sehen.
