### ISSUE TITLE
[Import] Add inline CRS support for GeoJSON

### ISSUE THREAD

**Issue by joergreichert** [Polymap4/polymap4-p4#37]
Spec: http://geojson.org/geojson-spec.html

http://www.sparkgeo.com/blog/encoding-geojson-geometry/

CRS in GeoJSON: http://gis.stackexchange.com/questions/15953/whats-up-with-the-geojson-spec-and-crs-as-a-irm

**Comment by stundzig** [comment]
GeoJSOn import works so far, but we need also support older GeoJSON files with embedded CRS in features. Thats not supported by the current geotools implementation, but the file load will be completely broken.

**Comment by stundzig** [comment]
https://github.com/stundzig/polymap4-p4/tree/task_37-Import_GeoJSON_v2 contains my current solution. Creating the Schema is working, but on parsing all features, its stop after the first coordinates are found.
