### ISSUE TITLE
[Import] KML

### ISSUE THREAD

**Issue by joergreichert** [Polymap4/polymap4-p4#38]
http://docs.geotools.org/latest/userguide/extension/xsd/kml.html
http://gis.stackexchange.com/questions/4549/how-to-parse-kml-data-using-geotools

Alternative: https://github.com/micromata/javaapiforkml

Example files: https://github.com/search?o=desc&p=5&q=geometry+extension%3Akml&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93

**Comment by stundzig** [comment]
Der Import funktioniert soweit, allerdings nur mit einem minimalen Support von dem was KML tatsächlich bietet.

javaapiforkml wird nicht mehr support seit März 2016, scheint trotzdem aber noch das aktuellste zu sein.  https://github.com/micromata/javaapiforkml/issues/18

Es fehlt noch 
- Unterstützung für Styling im KML
- Phonenumber und Address sollten nicht mit erzeugt werden
- KMZ kann mehrere KML's enthalten, momentan wird nur ein File Supported -> auf ZIP Importer umsetzen

**Comment by stundzig** [comment]
Die KML Referenz gibts bei https://developers.google.com/kml/documentation/kmlreference#placemark

**Comment by fb71** [comment]
Es scheint etwas zu funktionieren. Richtig probiert habe ich es noch nicht. Ich schließe das Ticket. Neue Anforderungen und/oder Bugs in neuen Tickets oder bitte mit konkreten Angaben wieder öffnen.
