### ISSUE TITLE
Excel import

### ISSUE THREAD

**Issue by stundzig** [Polymap4/polymap4-p4#41]
We need support to upload xls, xlsx from single and multisheet files. In multisheet mode, each sheet should become its own layer.

Similar to csv we need prompts to:
- select number of rows to ignore on start
- select number of headlines
- select number of rows to skip after headline
- select column with geometry
- if geometry exists, select CRS

**Comment by fb71** [comment]
The label "latitude/longitude" in prompt is wrong in most cases. For most CRS types the values are given in meters not degrees. Better would be something like: "Y/Hochwert (Breitengrad)"

**Comment by stundzig** [comment]
Its working now. Improvements and bugs are handled separately.
