### ISSUE TITLE
[Import] Import button is shown even if required actions exist

### ISSUE THREAD

**Issue by stundzig** [Polymap4/polymap4-p4#51]
The *import data* button in the import framework is visible, but red marked prompts are exists. The button must be hidden in this case.

![bildschirmfoto 2015-11-20 um 11 53 05](https://cloud.githubusercontent.com/assets/1140546/11298168/7f29adf6-8f7d-11e5-916c-b3b7c281b8e0.png)

**Comment by fb71** [comment]
CharsetPrompt to be REQUIRED is bad decision for shapefile. ISO-8859-1 is default encoding for shapefile. Other charset are used in real world but this not standard.

**Comment by fb71** [comment]
Und irgendwie fehlen alle Charsets. Ich sehe nur noch 3x ISO-???. Kein UTF kein Windows, kein nix!?

**Comment by stundzig** [comment]
-> https://github.com/Polymap4/polymap4-p4/issues/89
