### ISSUE TITLE
[Import] WMS: refresh of the preview

### ISSUE THREAD

**Issue by stundzig** [Polymap4/polymap4-p4#54]
I open the WMS importer, add an URL, click *Ok* but got nothing. No response or wait cursor or something else.

If i click of the prompt or importer again, then the preview gets reloaded.

See the video at https://www.youtube.com/watch?v=uFupXPHnEp4

**Comment by fb71** [comment]
Abstract/subject ist missing. I think it is part of the capabilities. It describes the contents of the service.

**Comment by fb71** [comment]
Content of the preview might become to big for the box in the UI. Scrollbars are needed.

**Comment by fb71** [comment]
Preview of the content would be really nice. All layers turned on? Switchable background layer?

And, all preview calculation MUST be async.

**Comment by stundzig** [comment]
Fixed, test it e.g. with https://www.govdata.de/web/guest/suchen/-/details/denkmaler-kreis-viersen-odp

Many of the WMS in govdata are broken e.g. with postgresql exceptions and other things.
