### ISSUE TITLE
[Import] OSM

### ISSUE THREAD

**Issue by joergreichert** [Polymap4/polymap4-p4#55]
- workflow
  - selection
  - select bounding box in already shown map resp. use zoomed in map as bounding box
  - additional/alternatively select geopolitical entity either in context of bounding box or without bounding box, i.e. countries, federal states, districts etc.
  - retrieve all tags in context of bounding box / entity
  - show tags in table or tree
  - select/unselect tags (preview in map required?)
  - import all features having at least one of the selected tags

**Comment by joergreichert** [comment]
![osm_importer_api_1](https://cloud.githubusercontent.com/assets/994131/11757134/3e9527dc-a05f-11e5-96ae-b833273270a2.png)
![osm_importer_api_2](https://cloud.githubusercontent.com/assets/994131/11757135/3e976f74-a05f-11e5-9a63-010557f5e475.png)

**Comment by fb71** [comment]
Code moved to https://github.com/Mapzone/mapzone-sdk
