### ISSUE TITLE
Layer "visibility" property

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-p4#60]
Tracking and handling of layer "visibility"

  - [x] #36
  - [x] #46

**Comment by joergreichert** [comment]
See also my attempts so far: 
https://github.com/Polymap4/polymap4-p4/pull/24
And the race condition with open layers: https://github.com/joergreichert/polymap4-core/commit/7031f2164db3df2436285a6c00918edd277b67be#diff-8be8cb133dd4b98fdcf99dd828e32556R201
