### ISSUE TITLE
[Import] CSV: zip file import doesnt work

### ISSUE THREAD

**Issue by stundzig** [Polymap4/polymap4-p4#72]
I've uploaded a zip file with 3 entries. 2 csv and 1 xls. The import shows these 3 files and also the Button to go to the next step, but then no data or preview are shown.

**Comment by fb71** [comment]
The org.polymap.p4.data.imports.refine.csv.CSVFileImporterFactory just does not handles multiple files in context. Nor does org.polymap.p4.data.imports.refine.excel.ExcelFileImporterFactory. Both are checking just for one single file in the context. See org.polymap.p4.data.imports.shapefile.ShpImporterFactory.
