### ISSUE TITLE
LayerInfoPanel

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-p4#76]
- [ ] visibilty of the layer in the map
- [x] basic field: name, keywords, description
- [ ] display properties: opacity (?) ...
- [ ] extendible dashboard
- [ ] legend graphic via decorating label provider (?)
- [ ] metadata: name, repo, quality, update, etc.
- [ ] map preview: features?, bounding box?
- [ ] extent, count
- [ ] shema
- [ ] comments, keywords (calculated?)

see also #61

**Comment by stundzig** [comment]
The *edit styling* action currently references to a wrong style. Seems to be the latest selected *featureSelection*, but the layerinfopanel shows a WMS layer.

**Comment by fb71** [comment]
I'm closing this. There are more specific tickets.
