### ISSUE TITLE
[Import] CSV: encodings are missing

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-p4#89]
A lot of important encodings are missing. Chinese (Big5), eastern european, etc. ... Where does the currently used list of possible encodings come from? 

We may (later?) have a fancy algorithm that guesses possible encodings from users's browser encoding. As long as this is not in place it is much better to show an overwhelming number of possibilities than to crowd out entire asia and most of europe from using our application!

The preview list in the selection is great. But it is too big on my screen/use-case. Set maximum width!

**Comment by stundzig** [comment]
OpenRefine offers a long list with all known encodings. And at the top of this list, a short list with the most important encodings. I've used only the important encodings and try to guess the encoding with the TypeGuesser.
