### ISSUE TITLE
[Import] Restrict number of features

### ISSUE THREAD

**Issue by stundzig** [Polymap4/polymap4-p4#98]
Not more than 100.000 features should be imported. If the data contains more than 100.000 entries, we should show a message to the user, that we are currently in Beta and will support more data later.

**Comment by fb71** [comment]
Maybe it's better to limit upload size!? Prevents "mega" uploads **before** to much CPUs cycles get wasted while processing to get the number of features. Or, even better, have both.

**Comment by stundzig** [comment]
What is a mega upload? More than 10MB?

**Comment by fb71** [comment]
It depends ;) Make it configurable via system property.

**Comment by fb71** [comment]
Upload is limited to 55M by nginx. That about 200-300.000 features. (?)
